---
name: varnish

addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm

instance_groups:
- name: varnish
  azs: [z1]
  instances: 1
  vm_type: default
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: varnish
    release: varnish
    properties:
      vcl_configuration: |
        vcl 4.1;
        backend default {
          .host = "www.example.org";
          .port = "80";
        }

      parameters:
      - name: default_ttl
        value: 0
      - name: nuke_limit
        value: 1000
      storage:
      - type: malloc
        options: 1G

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

stemcells:
  - alias: default
    os: ubuntu-xenial
    version: latest

releases:
- name: bpm
  version: latest
- name: varnish
  version: latest
