---
name: varnish

addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm

instance_groups:
- name: varnish
  azs: [z1]
  instances: 1
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: varnish
    release: varnish

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

stemcells:
  - alias: default
    os: ubuntu-xenial
    version: latest

releases:
- name: bpm
  version: latest
- name: varnish
  version: latest
